<?php
require_once('trinhchinhsua.php');
function descv_menu() {
    $items = array();
    $items['cv'] = array(
        'title' => 'Danh sách CV',
        'page callback' => 'descv_list',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'weight' => 0,
    );
    $items['cv/add'] = array(
        'title' => 'Thêm CV',
        'page callback' => 'descv_add',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'weight' => 1,
    );
    return $items;
}
function descv_list() {
    $build['add_cv_btn'] = array('#markup' => l('Add', 'cv/add', array('attributes' => array('class' => array('btn-green')))));
    $build['danhsach_cv'] = drupal_get_form('descv_list_form');
    // CSS, JS
      $build['#attached']['css'] = array(drupal_get_path('module', 'descv') . '/css/descv.css' => array('group' => CSS_THEME));
      $build['#attached']['js'] = array(drupal_get_path('module', 'descv') . '/js/descv.js' => array('group' => JS_THEME));    
    return $build;
}
function descv_add() {
    $build['backtolist'] = array('#markup' => l('Xem danh sách', 'cv', array('attributes' => array('class' => array('btn-green')))));
    $build['createcv'] = array('#markup' => '<div class="group-btn"><div class="btn-green btn-big" id="create-cv">TẠO CV </div></div>' );
    $build['trinhchinhsua_cv'] =  array('#markup' => trinhchinhsua_cv() );

    $build['add_cv'] = drupal_get_form('descv_add_cv');
    // CSS, JS
      $build['#attached']['css'] = array(drupal_get_path('module', 'descv') . '/css/descv.css' => array('group' => CSS_THEME));
      $build['#attached']['js'] = array(
          drupal_get_path('module', 'descv') . '/js/jquery.min.3.2.1.js' => array('group' => JS_THEME),
          drupal_get_path('module', 'descv') . '/js/load-add-cv.js' => array('group' => JS_THEME),
          'https://use.fontawesome.com/a31b73aa38.js' => array('type' => 'external',),
                                       );
    return $build;

}
///////////////////// FORM ////////////////////////////
function descv_list_form($form, &$form_state) {
    global $user;
      $select = db_select('cv', 'cv');
      $select->join('users', 'u', 'cv.uid = u.uid');
      $select->addField('cv', 'cvid');
      $select->addField('cv', 'time');
      $select->addField('u', 'name', 'username');
      $select->addField('cv', 'tieude');
      $select->condition('cv.uid', $user->uid, '=');

      $entries = $select->orderBy('time', 'DESC')->execute()->fetchAll(PDO::FETCH_ASSOC);
    
    $rows = array();
    $i = 1;
    foreach ($entries as $entry) {
    $entry = array_map('check_plain', $entry);
    $rows[$entry['cvid']] = array(date('Y-m-d H:i:s', $entry['time']), $entry['username'], $entry['tieude'], l('Sửa', 'cv/'.$entry['cvid'].''));
    }
    $header = array(t('Lần sửa cuối'),t('Tạo bởi'), t('Tiêu đề'), t('Edit'));
    $form['danhsach']['ids'] = array(
        '#type' => 'tableselect',
        '#caption' => 'DANH SÁCH CV',
        '#header' => $header,
        '#options' => $rows,
        '#empty' => 'Chưa có CV nào.',
      );
  $form['danhsach_cv']['pager'] = array('#markup' => theme('pager'));
  drupal_add_library('system', 'drupal.form');
    $form['danhsach_cv']['actions']['delete'] = array(
    '#type' => 'submit',
    '#value' => 'Delete',
    '#submit' => array('descv_delete_cv_submit'),
    '#attributes' => array('onclick' => 'if(!confirm("Bạn chắc chắn xóa các CV đã chọn?")){return false;}', 'class' => array('btn-del'))
  ); 
    return $form;
}
function descv_add_cv($form, &$form_state) {
    global $user;
    if(isset($_POST['info']['tieude'])) {
        $thongtin = array(
            'uid' => $user->uid,
            'tieude'     => $_POST['info']['tieude'],
            'time'     => time(),
            'anhdaidien'    => $_POST['info']['anhdaidien'],
            'hoten'     => $_POST['info']['hoten'],
            'vitrimongmuon'     => $_POST['info']['vitrimongmuon'],
            'sdt'       => $_POST['info']['sdt'],
            'email'     => $_POST['info']['email'],
            'ngaysinh'  => $_POST['info']['ngaysinh'],
            'gioitinh'  => $_POST['info']['gioitinh'],
            'diachi'    => $_POST['info']['diachi'],
            'website'       => $_POST['info']['website'],
            'sapxep'       => $_POST['info']['sapxep'],
        );
      $cvid = descv_thongtin_insert($thongtin, 'cv');
        // INSERT MUCTIEU
      $muctieu = array(
            'cvid' => $cvid,
            'muctieu' => $_POST['info']['muctieu'],
        );
     $idmuctieu = descv_thongtin_insert($muctieu, 'cv_muctieu');
        // INSERT KYNANG
      for($i = 0;$i < count($_POST['kynang']['loai']); $i++){
         $kynang = array(
                'cvid' => $cvid,
                'loai' => $_POST['kynang']['loai'][$i],
                'mucdo' => $_POST['kynang']['mucdo'][$i],
            );
         $idkynang = descv_thongtin_insert($kynang, 'cv_kynang');
        }
        // INSERT SOTHICH
        for($i = 0;$i < count($_POST['sothich']); $i++){
         $sothich = array(
                'cvid' => $cvid,
                'sothich' => $_POST['sothich'][$i],
            );
         $idsothch = descv_thongtin_insert($sothich, 'cv_sothich');
        }
        // INSERT NGUOITHAMCHIEU
        $thamchieu = array(
            'cvid' => $cvid,
            'thongtin' => $_POST['nguoithamchieu'],
        );
     $idthamchieu = descv_thongtin_insert($thamchieu, 'cv_thamchieu');
        // INSERT HOCVAN
      for($i = 0;$i < count($_POST['hocvan']['tentruong']); $i++){
         $hocvan = array(
                'cvid' => $cvid,
                'batdau' => $_POST['hocvan']['batdau'][$i],
                'ketthuc' => $_POST['hocvan']['ketthuc'][$i],
                'tentruong' => $_POST['hocvan']['tentruong'][$i],
                'nganh' => $_POST['hocvan']['nganh'][$i],
                'chitiet' => $_POST['hocvan']['chitiet'][$i],
            );
         $idhocvan = descv_thongtin_insert($hocvan, 'cv_hocvan');
        }
        // INSERT KINHNGHIEM
      for($i = 0;$i < count($_POST['kinhnghiem']['tencty']); $i++){
         $kinhnghiem = array(
                'cvid' => $cvid,
                'batdau' => $_POST['kinhnghiem']['batdau'][$i],
                'ketthuc' => $_POST['kinhnghiem']['ketthuc'][$i],
                'tencongty' => $_POST['kinhnghiem']['tencty'][$i],
                'vitri' => $_POST['kinhnghiem']['vitri'][$i],
                'chitiet' => $_POST['kinhnghiem']['chitiet'][$i],
            );
         $idkinhnghiem = descv_thongtin_insert($kinhnghiem, 'cv_kinhnghiem');
        }
         // INSERT HOATDONG
      for($i = 0;$i < count($_POST['hoatdong']['tentochuc']); $i++){
         $hoatdong = array(
                'cvid' => $cvid,
                'batdau' => $_POST['hoatdong']['batdau'][$i],
                'ketthuc' => $_POST['hoatdong']['ketthuc'][$i],
                'tentochuc' => $_POST['hoatdong']['tentochuc'][$i],
                'vitri' => $_POST['hoatdong']['vitri'][$i],
                'chitiet' => $_POST['hoatdong']['chitiet'][$i],
            );
         $idhoatdong = descv_thongtin_insert($hoatdong, 'cv_hoatdong');
        }
        // INSERT CHUNGCHI
      for($i = 0;$i < count($_POST['chungchi']['ten']); $i++){
         $chungchi = array(
                'cvid' => $cvid,
                'ten' => $_POST['chungchi']['ten'][$i],
                'thoigian' => $_POST['chungchi']['thoigian'][$i],
            );
         $idchungchi = descv_thongtin_insert($chungchi, 'cv_chungchi');
        }
        // INSERT GIAITHUONG
      for($i = 0;$i < count($_POST['giaithuong']['ten']); $i++){
         $giaithuong = array(
                'cvid' => $cvid,
                'ten' => $_POST['giaithuong']['ten'][$i],
                'thoigian' => $_POST['giaithuong']['thoigian'][$i],
            );
         $idgiaithuong = descv_thongtin_insert($giaithuong, 'cv_giaithuong');
        }
        // INSERT THÔNG TIN THÊM
        $them = array(
            'cvid' => $cvid,
            'thongtin' => $_POST['them'],
        );
     $idthem = descv_thongtin_insert($them, 'cv_them');
        // END
      if ($cvid) {
        drupal_set_message(t("Đã tạo CV: @title", array('@title' => print_r($cvid, TRUE))));
        drupal_goto('cv');
      }
    }
}
function descv_delete_cv_submit($form, &$form_state) {
    global $user;
    $values = $form_state['values'];
    $ids = array_filter($values['ids']);
    if(count($ids) == 0) {
        form_set_error('ids', 'Vui lòng chọn ít nhất một CV.');
        return;
    }
    $return = descv_entry_delete($ids);
    if($return) {
        drupal_set_message(t("Đã xóa thành công các CV đã chọn!!"));
        drupal_goto('cv');
    }
    return;
}
/// ADD MORE, REMOVE ONE MỤC TIÊU
function muctieu_callback($form, $form_state) {
  return $form['muctieu'];
}
function add_more_muctieu($form, &$form_state) {
  $form_state['num_muctieu']++;
  $form_state['rebuild'] = TRUE;
}
function remove_one_muctieu($form, &$form_state) {
  if ($form_state['num_muctieu'] > 1) {
    $form_state['num_muctieu']--;
  }
  $form_state['rebuild'] = TRUE;
}
//////// INSERT, UPDATE
function descv_thongtin_insert($entry, $table) {
  $return_value = NULL;
  try {
    $return_value = db_insert($table)
                    ->fields($entry)
                    ->execute();
  }
  catch (Exception $e) {
    drupal_set_message(t('db_insert failed. Message = %message, query= %query',
      array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
  }
  return $return_value;
}

function descv_entry_delete($ids) {
    $return_value = NULL;
    $trans = db_transaction();
    try {
    $return_value = db_delete('cv')
    ->condition('cvid', $ids, 'IN')
    ->execute();
        if($return_value) {
    db_delete('cv_muctieu')->condition('cvid', $ids, 'IN')->execute();
    db_delete('cv_kynang')->condition('cvid', $ids, 'IN')->execute();
    db_delete('cv_sothich')->condition('cvid', $ids, 'IN')->execute();
    db_delete('cv_thamchieu')->condition('cvid', $ids, 'IN')->execute();
    db_delete('cv_hocvan')->condition('cvid', $ids, 'IN')->execute();
    db_delete('cv_kinhnghiem')->condition('cvid', $ids, 'IN')->execute();
    db_delete('cv_hoatdong')->condition('cvid', $ids, 'IN')->execute();
    db_delete('cv_chungchi')->condition('cvid', $ids, 'IN')->execute();
    db_delete('cv_giaithuong')->condition('cvid', $ids, 'IN')->execute();
    db_delete('cv_them')->condition('cvid', $ids, 'IN')->execute();
        }
    } catch (Exception $e) {
        $trans->rollback();
        form_set_error('error', 'Lỗi không thể xóa:'.$e->getMessage().'.');
    }
    return $return_value;
}
?>
 